import './assets/style.css'
import { createApp } from 'vue'
import App from './App.vue'
import navbar from './components/navbar.vue';
import footer from './components/footer.vue';
import router from './router/router.js';
import newRelase from './components/newRelase.vue';
import topRated from './components/topRated.vue';
import movieFilter from './components/filters/movieFilter.vue';
import compMovie from './components/compMovie.vue';
import compTvShow from './components/compTvShow.vue';
import TvSeriesFilter from './components/filters/TvSeriesFilter.vue';
import allMovie from './components/filters/allMovie.vue';
import actionFilter from './components/filters/actionFilter.vue';
import adventureFilter from './components/filters/adventureFilter.vue';
import documentaryFilter from './components/filters/documentaryFilter.vue';
import hororFilter from './components/filters/hororFilter.vue';
import romanceFilter from './components/filters/romanceFilter.vue';
import thrillerFilter from './components/filters/thrillerFilter.vue';
import dramaFilter from './components/filters/dramaFilter.vue';
import comedyfilter from './components/filters/comedyfilter.vue';
import animationFilter from './components/filters/animationFilter.vue';
const app = createApp(App);
app.component('Navbar', navbar);
app.component('Footer', footer);
app.component('new-relase', newRelase);
app.component('top-rateds', topRated);
app.component('movieFilter', movieFilter);
app.component("TvSeriesFilter", TvSeriesFilter);
app.component('compMovie', compMovie);
app.component("compTvShow", compTvShow);
app.component("allMovie", allMovie);
app.component("actionFilter", actionFilter);
app.component("documentaryFilter", documentaryFilter);
app.component("adventureFilter", adventureFilter);
app.component("hororFilter", hororFilter);
app.component("romanceFilter", romanceFilter);
app.component("thrillerFilter", thrillerFilter);
app.component("dramaFilter", dramaFilter);
app.component("comedyFilter", comedyfilter);
app.component("animationFilter", animationFilter);
app.use(router);
app.mount('#app');
